apiVersion: v1
kind: Service
metadata:
  name: {{ include "routify.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "routify.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "routify.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api