apiVersion: v1
kind: Service
metadata:
  name: {{ include "routify.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "routify.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "routify.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway