apiVersion: v2
name: routify
description: Helm charts for Routify AI
type: application
version: 0.1.0
appVersion: "0.1.2"

dependencies:
  - name: postgresql
    version: "^15"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "^19"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
